### ISSUE TITLE
Text to Speech

### ISSUE THREAD

**Issue by Crypta-Eve** [Crypta-Eve/provi-i#1]
Implement a cross-platform text to speech solution to augment the alarm system.
As it stands this exists but only for Mac users.

**Comment by AndrisArickson** [comment]
Is it useful for the Mac users? Can we get some comments to determine it's worthiness of dev time?

**Comment by Crypta-Eve** [comment]
To be completely honest the fact that it is available to mac users is legacy from the original project, at this stage I need to find people who play on mac regularly anyway for feedback as I dont know anyone who uses it regularly.

**Comment by Crypta-Eve** [comment]
After speaking to a handful of Mac users, they do not find the feature useful. For now I am going to close this as it is quite a low priority. However the idea is there for future reference, once code has been stripped then the dependency on pyttsx can also be removed.
