### ISSUE TITLE
Compact Provi-Catch map clipping

### ISSUE THREAD

**Issue by AndrisArickson** [Crypta-Eve/provi-i#12]
When using the "Provi / Catch (compact)" map the edge systems are clipped.
Linux using source 1.1.1

![provi-catch](https://cloud.githubusercontent.com/assets/26018180/23584495/63553a9c-01b3-11e7-8ab7-098b1c000dbe.png)

**Comment by Crypta-Eve** [comment]
Ahh, Yeah that shouldnt thappen 😄 , looking into it now.....

**Comment by Crypta-Eve** [comment]
This is a problem with the svg delivered by dotlan, the dimensions are not accurate to the image size needed.
