### ISSUE TITLE
Intel Auto Scan has no loading indicator

### ISSUE THREAD

**Issue by tehraven** [Crypta-Eve/provi-i#16]
Enabling Intel Auto Scan and then restarting the application works as expected -- the intel from chat files are loaded to show known information from before the app was launched. However, this process has no loading indication, so the application will appear frozen and non-interactive.

**Comment by Crypta-Eve** [comment]
Very true, after the gui rebuild this shouldn't be the case. It will happen in the background. I'll look at adding an indicator of this happening though.
