### ISSUE TITLE
virustotal results for your app

### ISSUE THREAD

**Issue by raykai** [Crypta-Eve/provi-i#17]
you may want to try and fix this ...
 [https://www.virustotal.com/en/file/ed80790a95e29a00faefdc5534a14756fb84e1a4f8f24c67309c8070b7da4602/analysis/1505202698/](https://www.virustotal.com/en/file/ed80790a95e29a00faefdc5534a14756fb84e1a4f8f24c67309c8070b7da4602/analysis/1505202698/)

**Comment by Crypta-Eve** [comment]
This is an issue which exists for a large number of projects. The reason for it is that I use PyInstaller to create the standalone executable file. PyInstaller packages all the files in the exe, then at runtime unpacks to a temporary directory and runs from there... Virus scans dont really like this... I have sent in the file for analysis to the relevant AV scanners, however have had little success in getting an exception so far.

Though it is something I am working on. Also my code signing certificate should be with me in the next few days so expect to see a minor version bump with a new signed exe.

**Comment by raykai** [comment]
alright :)
