### ISSUE TITLE
Spyglass crashing after new router install

### ISSUE THREAD

**Issue by Yyrkoon62** [Crypta-Eve/provi-i#21]
Ever since I installed my new router I can't get Spyglass to run.  Crashes immediately.

Screenshot attached.
![screenshot](https://user-images.githubusercontent.com/36686066/36462015-1c4d59e6-167e-11e8-9bee-f5387787f9ad.jpg)

**Comment by petsagouris** [comment]
I solve that error message by deleting the folder "spyglass" in:

    C:\Users\<user>\Documents\EVE\spyglass

**Comment by Crypta-Eve** [comment]
Going to put it that the timing may be a coincidence.... But as stated above deleting that folder will clear a corrupted cache which is in 99.999% of cases the issue.
