### ISSUE TITLE
Check for previous intel

### ISSUE THREAD

**Issue by Crypta-Eve** [Crypta-Eve/provi-i#3]
On startup read past logs in order to see if there is any recent intel to add. Also on region change, recolour the map with known intel.

**Comment by AndrisArickson** [comment]
Super useful to keep the previous intel in the stack. Not sure if you want to scan back in time for all previous intel as the possibility of many intel channels could make for too many instructions and a crash. IF the scan back in time option does actually work it would be awesome, app would check history of chat when started and produce up to date intel picture. Worth moving to a separate issue. #3 would be keep existing intel in stack #3a would be do a 30 minute / 1 hour / etc / grep back through intel channel chat logs and update intel picture.

**Comment by Crypta-Eve** [comment]
Your right in that people will most likely never have cleared their chat logs and this will be massive to scan through, however the way I am currently working on it; the logs will be checked for the last modified time and if that is within the last 20m then scan that log for intel. Still means accessing all logs, however it is better than parsing them all.
